config_setting(
    name = "windows",
    constraint_values = [
        "//os/constraints:windows",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "linux",
    constraint_values = [
        "//os/constraints:linux",
    ],
    visibility = ["PUBLIC"],
)
