constraint_setting(
    name = "cpu",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "x86_64",
    constraint_setting = ":cpu",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "aarch64",
    constraint_setting = ":cpu",
    visibility = ["PUBLIC"],
)
