config_setting(
    name = "release",
    constraint_values = [
        "//build_type/constraints:release",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "rel_with_deb_info",
    constraint_values = [
        "//build_type/constraints:rel_with_deb_info",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "debug",
    constraint_values = [
        "//build_type/constraints:debug",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "docs",
    constraint_values = [
        "//build_type/constraints:docs",
    ],
    visibility = ["PUBLIC"],
)
